[workspace.dependencies]
regex = "^1.11"
thiserror = "^2.0"
util = { path = "util" }

[workspace]
members = ["util", "year2024/day01", "year2024/day02", "year2024/day03", "year2024/day04", "year2024/day05", "year2024/day06", "year2024/day07"]
resolver = "2"